version: "3.9"
services:
  javasnippet:
    build: ./javasnippet/
    ports:
      - "8000:8000"
  pythonsnippet:
    build: ./pythonsnippet/
    ports:
      - "8001:8001"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "5775:5775/udp"
      - "14250:14250"
      - "9411:9411"
      - "14269:14269"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
